'use client';

import React, { useState, useEffect } from 'react';
import { Save, Plus, ArrowLeft, Trash2, Loader } from 'lucide-react';
import Link from 'next/link';

export function AdminCreateQuoteManager() {
  const [loading, setLoading] = useState(false);
  const [products, setProducts] = useState<any[]>([]);
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    company: '',
    gstNumber: '',
    message: 'Manual quote generated by Admin.',
  });
  const [items, setItems] = useState<any[]>([{ productId: '', quantity: 1, rate: 0, gstRate: 0, notes: '' }]);

  useEffect(() => {
    fetch('/api/admin/products?take=100')
      .then((res) => res.json())
      .then((data) => {
        if (data.products) setProducts(data.products);
      });
  }, []);

  const handleAddItem = () => {
    setItems([...items, { productId: '', quantity: 1, rate: 0, gstRate: 0, notes: '' }]);
  };

  const handleRemoveItem = (index: number) => {
    const newItems = [...items];
    newItems.splice(index, 1);
    setItems(newItems);
  };

  const handleItemChange = (index: number, field: string, value: any) => {
    const newItems = [...items];
    newItems[index] = { ...newItems[index], [field]: value };
    setItems(newItems);
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      // Create enquiry first
      const res = await fetch('/api/enquiries', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...formData,
          items: items.filter(i => i.productId).map(i => ({
            productId: i.productId,
            quantity: i.quantity,
            notes: i.notes,
          }))
        }),
      });
      if (!res.ok) throw new Error('Failed to create enquiry');
      const data = await res.json();
      
      // Update with quote data
      let subtotal = 0;
      let gstTotal = 0;
      items.forEach(i => {
        const lineTotal = (i.rate || 0) * i.quantity;
        const lineGst = lineTotal * (i.gstRate || 0) / 100;
        subtotal += lineTotal;
        gstTotal += lineGst;
      });

      const quoteRes = await fetch(`/api/admin/enquiries/${data.enquiryId}/quote`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          isQuote: true,
          items: data.items, // wait, the items returned by create-enquiry don't have rate/gstRate populated in the client yet.
          bankDetails: 'Please add bank details here.',
          subtotal,
          gstTotal,
          grandTotal: subtotal + gstTotal,
        })
      });
      
      // Redirect to the edit page
      window.location.href = `/admin/enquiries/${data.enquiryId}`;
    } catch (err) {
      console.error(err);
      alert('Failed to create quote');
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center gap-4">
        <Link href="/admin/enquiries" className="p-2 rounded-full hover:bg-gray-100 text-gray-500">
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <h1 className="text-xl font-bold font-sans text-gray-900">Create Manual Quote</h1>
      </div>

      <form onSubmit={handleSave} className="space-y-6 bg-white p-6 rounded-xl shadow-sm border border-gray-200">
        <h3 className="font-bold text-gray-900">Client Details</h3>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">Name *</label>
            <input required type="text" value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} className="w-full rounded-lg border-gray-300 text-sm focus:border-red-500 focus:ring-red-500" />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">Email *</label>
            <input required type="email" value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} className="w-full rounded-lg border-gray-300 text-sm focus:border-red-500 focus:ring-red-500" />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">Phone</label>
            <input type="text" value={formData.phone} onChange={e => setFormData({...formData, phone: e.target.value})} className="w-full rounded-lg border-gray-300 text-sm focus:border-red-500 focus:ring-red-500" />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">Company</label>
            <input type="text" value={formData.company} onChange={e => setFormData({...formData, company: e.target.value})} className="w-full rounded-lg border-gray-300 text-sm focus:border-red-500 focus:ring-red-500" />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-700 mb-1">GST Number</label>
            <input type="text" value={formData.gstNumber} onChange={e => setFormData({...formData, gstNumber: e.target.value})} className="w-full rounded-lg border-gray-300 text-sm focus:border-red-500 focus:ring-red-500" />
          </div>
        </div>

        <h3 className="font-bold text-gray-900 mt-6 pt-6 border-t border-gray-200">Quote Items</h3>
        <div className="space-y-4">
          {items.map((item, index) => (
            <div key={index} className="flex gap-4 items-end bg-gray-50 p-4 rounded-lg border border-gray-200">
              <div className="flex-1">
                <label className="block text-xs font-medium text-gray-700 mb-1">Product *</label>
                <select required value={item.productId} onChange={e => handleItemChange(index, 'productId', e.target.value)} className="w-full rounded-lg border-gray-300 text-sm focus:border-red-500 focus:ring-red-500">
                  <option value="">Select Product...</option>
                  {products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                </select>
              </div>
              <div className="w-24">
                <label className="block text-xs font-medium text-gray-700 mb-1">Qty</label>
                <input required type="number" min={1} value={item.quantity} onChange={e => handleItemChange(index, 'quantity', parseInt(e.target.value))} className="w-full rounded-lg border-gray-300 text-sm focus:border-red-500 focus:ring-red-500" />
              </div>
              <div className="w-32">
                <label className="block text-xs font-medium text-gray-700 mb-1">Rate (₹)</label>
                <input type="number" min={0} value={item.rate} onChange={e => handleItemChange(index, 'rate', parseFloat(e.target.value))} className="w-full rounded-lg border-gray-300 text-sm focus:border-red-500 focus:ring-red-500" />
              </div>
              <div className="w-24">
                <label className="block text-xs font-medium text-gray-700 mb-1">GST (%)</label>
                <input type="number" min={0} value={item.gstRate} onChange={e => handleItemChange(index, 'gstRate', parseFloat(e.target.value))} className="w-full rounded-lg border-gray-300 text-sm focus:border-red-500 focus:ring-red-500" />
              </div>
              <button type="button" onClick={() => handleRemoveItem(index)} className="p-2 text-red-600 hover:bg-red-50 rounded-lg">
                <Trash2 className="w-5 h-5" />
              </button>
            </div>
          ))}
          <button type="button" onClick={handleAddItem} className="px-4 py-2 text-sm font-semibold text-gray-700 bg-white border border-gray-300 rounded-lg shadow-sm hover:bg-gray-50 flex items-center gap-2">
            <Plus className="w-4 h-4" /> Add Item
          </button>
        </div>

        <div className="mt-6 pt-6 border-t border-gray-200 flex justify-end">
          <button type="submit" disabled={loading} className="px-6 py-2.5 bg-gray-900 text-white rounded-lg font-semibold text-sm hover:bg-gray-800 flex items-center gap-2">
            {loading ? <Loader className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />} Create Quote
          </button>
        </div>
      </form>
    </div>
  );
}
